server:
  port: 8082
kafka:
  topic:
    reservation:
      create: reservation-created
      update: reservation-updated
      delete: reservation-deleted
spring:
  application:
    name: reservation-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
